---
title: "CHE 318 Lecture 05"
subtitle: "Molecular Diffusivity: Theories and Measurement"
author: "Dr. Tian Tian"
date: "2026-01-14"
format:
  html: {}
  revealjs:
    output-file: slides.html
---

::: {.content-visible when-format="html" unless-format="revealjs"}

::: {.callout-note}
Slides 👉  [Open presentation🗒️](./slides.html)
:::

:::

## Recap

- Theories for predicting gas diffusivity $D_{AB}$:
  - Kinetic theory (inaccurate)
  - Chapman-Enkog theory (high accuracy, hard to use)
  - Fuller method (trade off)

- Estimating $\sum \nu_i$ using Fuller method table
- Extrapolating $D_{AB}$ at different $(T, P)$
- Solving examples


## Learning Outcomes {.center}

After today's lecture, you will be able to:

- **Recall** differences between diffusion in gas and in liquid 
- **Describe** the limiting cases of mass transport in liquid
- **Solve** EMCD, stagnant B and general cases for transport in liquid
- **Analyze** analogs between mass transport solution in gas and liquid

## Diffusion in Liquid

Recall our general transport phenomena equation in [Lecture 1](../L01)

$$
\text{[rate of transfer process]} = 
\dfrac{\text{[driving force]}}{\text{[resistance]}}
$$

Let $A$ being a soluble species, $B$ being the liquid.  The resistance
in liquid for diffusive transport is much larger than in gases:

1) Molecular density of liquid (_value_) is much higher than gas (_value_)
  - Intermolecular interaction in liquid is dominating (in comparison, kinetic effect in gases)
  - $D_{AB}\vert_{l} \approx 10^{-5} D_{AB}\vert_{g}$
  - $D_{AB}\vert_{l} \approx 10^{-12} \sim 10^{-10}\ \text{m}^2\cdot\text{s}^-1$
  
2) $D_{AB}\vert_{l}$ is usually dependent on the molar fraction of $A$
  - In this lecture we will use the diluted limit
  - $D_{AB}\vert_{l} \neq f(c_A)$

---

## Mass Transport in Liquid -- Example 1 EMCD

The equimolar counter diffusion (EMCD) case in liquid also satisfies $N_A + N_B = 0$

From notes in [Lecture 2](../L02), we can directly write the solution for $N_A$:

```{=tex}
N_A &= \frac{D_{AB}{z_2 - z_1} (c_{A1} - c_{A2}) \\
  &= \frac{D_{AB} c_{A, v}}{z_2 - z_1} (x_{A1} - x_{A2})   
```

$c_{av}$ is the average total concentration in A+B, defined as:

$$
c_{av} = \left(\frac{\rho}{M}\right) = \frac{1}{2} \left(\frac{\rho_1}{M_1} + \frac{\rho_2}{M_2}\right) 
$$
where
- $\rho_1$ and $\rho_2$ are average density of solution at points 1 and 2
- $M_1$ and $M_2$ are average molecular weight of the solution at points 1 and 2
- What is the assumption if we can use the average $c_{av}$ in this case?




---

## Summary

- Compare diffusion in gas and in liquid
- $D_{AB}\vert_{l} \ll D_{AB}\vert_{g}$
- Theories for predicting diffusivity in liquid, and when to apply them
- 



---

