---
title: "CHE 318 Lecture 14"
subtitle: "Mass Transfer Coefficients (II)"
author: "Dr. Tian Tian"
date: "2026-02-04"
format:
  html: {}
  revealjs:
    output-file: slides.html
  pdf:
    output-file: L14.pdf
---

::: {.content-visible when-format="html" unless-format="revealjs"}

::: {.callout-note}
- Slides 👉  [Open presentation🗒️](./slides.html)
- PDF version of course note  👉 [Open in pdf](./L14.pdf)
- Handwritten notes 👉 [Open in pdf](./public/L14_annotated.pdf)
:::

:::

## Recap {.center}

- Introduction to mass transfer coefficients
- Link between mass transfer coefficient and diffusivity
- Introduction to boundary concentration problem


## Learning Outcomes {.center}

After today's lecture, you will be able to:

- Remember the flux equations using mass transfer coefficient in different phases
- Recall the motivation of using mass transfer coefficient
- Analyze mass transfer coefficients' units
- Distinguish between mass transfer coefficients in different forms

## Mass Transfer Coefficient In Different Forms

When using $k$ to express flux, we have the **same form** (_Geankoplis Table 7.2.1_)

- Flux equations for EMCD

```{=tex}
\begin{align}
\text{Gases:}\quad 
N_A 
&= k_c'\,(c_{A1}-c_{A2})
= k_G'\,(p_{A1}-p_{A2})
= k_y'\,(y_{A1}-y_{A2})
\\
\text{Liquids:}\quad 
N_A 
&= k_c'\,(c_{A1}-c_{A2})
= k_L'\,(c_{A1}-c_{A2})
= k_x'\,(x_{A1}-x_{A2})
\end{align}
```

- Flux equations for diffusion through stagnant B

```{=tex}
\begin{align}
\text{Gases:}\quad 
N_A 
&= k_c\,(c_{A1}-c_{A2})
= k_G\,(p_{A1}-p_{A2})
= k_y\,(y_{A1}-y_{A2})
\\[4pt]
\text{Liquids:}\quad 
N_A 
&= k_c\,(c_{A1}-c_{A2})
= k_L\,(c_{A1}-c_{A2})
= k_x\,(x_{A1}-x_{A2})
\end{align}
```

But:

- $k_c'$ and $k_c$ are two different coefficients
- $k_c'$, $k_L'$, $k_G'$ have different units

## Naming Convention and Units

- Superscript: EMCD $k'_{\text{driving force}}$; Convective / stagnant B $k_{\text{driving force}}$

| Phase / Driving force | Concentration $c_A$          | Partial pressure $p_A$                                            | Mole fraction<br/>(gas $y_A$, liquid $x_A$)                             |
|-----------------------|------------------------------|-------------------------------------------------------------------|-------------------------------------------------------------------------|
| Gas phase             | $k_c$, $k_c'$                | $k_G$, $k_G'$                                                     | $k_y$, $k_y'$                                                           |
| Liquid phase          | $k_c$, $k_c'$                | –                                                                 | $k_x$, $k_x'$                                                           |
| Liquid (alt. form)    | $k_L$, $k_L'$                | –                                                                 | –                                                                       |
| Unit of $k$                  | $\text{m}\cdot\text{s}^{-1}$ | $\dfrac{\text{kg mol}}{\text{s} \cdot \text{m}^2 \cdot \text{Pa}}$ | $\dfrac{\text{kg mol}}{\text{s} \cdot \text{m}^2 \cdot \text{mol frac}}$ |

## Conversions Between Mass Transfer Coefficients

:::{.columns}
:::{.column width="50%"}
**Gas phase**

```{=tex}
\begin{align}
k_c' \, c
&= k_c' \frac{p}{RT}
= k_c \frac{p_{Bm}}{RT}
\\
&= k_G' \, p
= k_G \, p_{BM}
\\
&= k_y' 
= k_y \, y_{BM}
\\
&= k_c \, y_{BM} \, c
= k_G \, y_{BM} \, p
\end{align}
```

- $p$ : total pressure
- $p_{BM}$ : log-mean partial pressure of inert $B$
- $y_{BM}$ : log-mean mole fraction of $B$
- $c = p/(RT)$


:::

:::{.column width="50%"}

**Liquid phase**

```{=tex}
\begin{align}
k_c' \, c
&= k_L' \, c
= k_L \, x_{Bm} \, c
\\
&= k_L' \, \frac{\rho}{M}
= k_x'
= k_x \, x_{Bm}
\end{align}
```

- $\rho$ : liquid density
- $M$ : molecular weight
- $x_{Bm}$ : log-mean mole fraction of solvent $B$


:::
:::

## Example 1: Convective Flux Through A Tube


Question: Consider steady-state, one-dimensional mass transfer of a
binary gas mixture consisting of species $A$ and $B$ between two
parallel planes, labeled (1) and (2). The total pressure of the system
is $p_T = 700 \text{kPa}$ and the temperature is maintained at $T =
100 ^\circ\text{C}$. The gas-phase mass transfer coefficient from molar fraction is
$ k_y’ = 1.5 \times 10^{-4} \text{kg mol}\cdot \text{m}^{-2} \cdot \text{s}^{-1}$.

1. Find the values for fluxes $N_A$ and $N_B$
2. Find the values (and units) for other coefficients $k_G'$ and $k_c'$


## Solutions To Example 1

:::{.callout-tip}
- Mass transport normal to fluid can usually use $k$ to write the flux equation
- Pay attention to the unit used
:::

Answer

1. $N_A = -N_B = 3.0\times 10^{-5}\ \text{kg mol}\cdot \text{m}^{-2} \cdot \text{s}^{-1}$
2. $k_G' = k_y' / p_T = 2.14\times 10^{-7}\ \text{kg mol}/(\text{m}^2 \cdot \text{s} \cdot {kPa})$
3. $k_c' = k_y' RT / p_T = 6.65\times 10^{-4}\ \text{m}\cdot \text{s}^{-1}$

## Example 2: Using $k$ For Diffusion Through Stagnant Film

_Geankoplis Ex 7.2-1_ Alarge volume of pure gas $B$ at 2 atm pressure
flows over a flat surface. Species $A$ is vaporizing from the surface
into the gas stream. The liquid $A$ completely wets the surface of a
blotting paper, so that the interface is always covered with liquid
$A$. The partial pressure of species $A$ at $298\;\text{K}$ is
$0.20\;\text{atm}$. 
From textbook table, 
$$ k_y' = 6.78 \times 10^{-5} \;\frac{\text{kg mol}}{\text{m}^2 \cdot \text{s}}$$.

Calculate the evaporation rate $N_A$ and determine the values of the gas-phase mass transfer coefficients $k_y$ and $k_G$ for this system.

## Solutions To Example 2

:::{.callout-tip}
- This is a diffusion through stagnant B system
- Convert $k_y'$ to $k_y$ in stagnant B system first
- Express $k_G$ in $\text{kg mol}/(\text{s} \cdot \text{m}^2 \cdot \text{atm})$ first
:::

Answer

1. $y_{Bm} = 0.95$  👉 
$k_y = k_y'/y_{Bm} = 7.138\times 10^{-5} \;\frac{\text{kg mol}}{\text{m}^2 \cdot \text{s}}$
2. $y_G = 3.569 \times 10^{-5}\ \text{kg mol}/(\text{s} \cdot \text{m}^2 \cdot \text{atm})$
3. $N_A = y_G (p_{A1} - p_{A2}) = 7.138 \times 10^{-6}\ \text{kg mol}\cdot \text{m}^{-2} \cdot \text{s}^{-1}$

## Example 3: Measuring $k$ For Actual Systems

Since we have $\text{[Flux]} = k \times \text{[Driving Force]}$, we can measure $k$ using given geometries.

Question: solid benzoic acid (A) in a sphere with radius $r_0$ was
place in a tube with water flowing in the system. The fluid was turned
on for a certain time interval $\Delta t$ to remove dissolved A from
the liquid. The masses of a dried sphere before and after the
experiment were measured to be $m_1$ and $m_2$ ($m_2 - m_1 \ll
m_1$). The solubility of A in water is $c_{As}$ and water contain no
benzoid acid. Calculate the mass transfer coefficient of this
system. What form of $k$ did you use?

## Solutions To Example 3

:::{.callout-tip}
- Flow-induced flux, can be turbulent  👉 lumped $k_L$ term is valid
- Link $N_A$ to mass loss rate
:::

Answer:

- Relating flux equation to mass loss rate:
```{=tex}
\begin{align}
N_A &= \frac{1}{4 \pi r_0^2} \frac{m_1 - m_2}{M_A \Delta t} \\
&= k_L (c_{As} - 0)
\end{align}
```
- Solve for $k_L$:

```{=tex}
\begin{align}
k_L = \frac{1}{4 \pi r_0^2} \frac{m_1 - m_2}{c_{As} M_A \Delta t}
\end{align}
```

## Mass Transfer Coefficients For Various Geometries

- Expressing fluxes using $k$ coefficients are easy
- But do we need to measure $k$ for each system specifically?
- Of course **NO**!
- We can correlate the values of $k$ measured in different geometries, velocities using **dimensionless numbers**
- Similar treatment exists in heat and momentum (fluid) transfer

## Dimensionless Numbers In Mass Transfer

- **Schmidt number** (ratio between momentum diffusivity and molecular diffusivity)

```{=tex}
\begin{align}
N_{\text{Sc}} = \frac{\mu}{\rho D_{AB}}
\end{align}
```

- **Sherwood number** (ratio between convective mass transfer and molecular mass transfer)

```{=tex}
\begin{align}
N_{\text{Sh}} = \frac{k_c' L}{D_{AB}}
\end{align}
```

- **Reynolds number** (ratio between kinetic vs viscous forces of fluid flow)

```{=tex}
\begin{align}
N_{\text{Re}} = \frac{L v \rho}{\mu}
\end{align}
```

## How Are $k_c'$ Correlated By Dimensionless Numbers?

- Idea: mass transfer in flowing fluid described by $v$, $\rho$, $\mu$, $c$, $D_{AB}$ and geometry (characteristic length $L$)
- The combinations of these properties --> dimensionless number groups ($N_{\text{Sc}}$, $N_{\text{Sh}}$, $N_{\text{Re}}$)
- The Chilton-Colburn $j$-factor analog has most successful use in mass transfer

```{=tex}
\begin{align}
j_D &= \frac{k_c'}{v_{av}} (N_{\text{Sc}})^{2/3} \\
    &= \boxed{\frac{k_c' L}{D_{AB}}} \boxed{\frac{\rho D_{AB}}{\mu}} \boxed{\frac{\mu}{L v_{av} \rho}} (N_\text{sc})^{2/3} \\
	&= N_{\text{Sh}} N_{\text{Sc}}^{-1} N_{\text{Re}}^{-1} (N_\text{sc})^{2/3} \\
	&= \frac{N_{\text{Sh}}}{N_{\text{Re}} N_{\text{Sc}}^{1/3}}
\end{align}
```
















## Summary

- Good luck with the midterm exam!








