---
title: "CHE 318 Lecture 11"
subtitle: "Unsteady State Mass Transfer"
author: "Dr. Tian Tian"
date: "2026-01-28"
format:
  html: {}
  revealjs:
    output-file: slides.html
  pdf:
    output-file: L11.pdf
---

::: {.content-visible when-format="html" unless-format="revealjs"}

::: {.callout-note}
- Slides 👉  [Open presentation🗒️](./slides.html)
- PDF version of course note  👉 [Open in pdf](./L11.pdf)
- Handwritten notes 👉 [Open in pdf](./public/L11_annotated.pdf)
:::

:::

## Recap {.center}

- Step-by-step solution to U.S.S. evaporation through stagnant air
- Mass balance & flux analysis for catalyst on wall system


## Learning outcomes {.center}

After this lecture, you will be able to:

- **Recall** how reaction terms enter diffusion equations.
- **Identify** boundary and initial conditions for reaction-related transport problems.
- **Apply** simplifying assumptions to unsteady-state reaction-diffusion models.
- **Analyze** how reaction terms alter concentration profiles and controlling behavior.


## U.S.S example 2: transport through a reactive wall

**Question**: A gas mixture of CO$_2$ (A) in argon (B) is flown
through a cylindrical pipe of diameter $D$ and length $L$ with
constant velocity $v_m$. The pipe is covered with a porous material to
absorb CO$_2$. The porous material is coated uniformed on the inner
wall of the pipe. While A is flowing through the pipe, it is being absorbed by a first-order reaction

$$ 
r_A =
k(c_{A,s} - c_A) 
$$

Where $c_{A, s}$ is the surface concentration on the absorbing
material and $c_A$ is the conentration of A in the gas mixture. We
assume the concentration $c_A(z)$ in the gas phase is uniform in the
radial direction. The total pressure $p_T$ and temperature $T$ are both kept constant.

Can you estimate the concentration of CO$_2$ at the end of the pipe?


## Step 1: mass balance

Consider a differential gas-phase control volume of thickness $\Delta z$ that intersects the catalytic wall.

```{=tex}
\begin{align}
\text{In} - \text{Out} + \text{Generation} &= \text{Accumulation} \\
\\
\frac{\pi D^2}{4}
\left(
N_A\big|_{z}
-
N_A\big|_{z+\Delta z}
\right)
+
\pi D\,\Delta z\,k\,(c_{A,s}-c_A)
&=
\frac{\pi D^2}{4}\,
\frac{\partial C_A}{\partial t} \\
-\frac{\partial N_A}{\partial z}
+
\frac{4k}{D}\,(c_{A,s}-c_A)
=
\frac{\partial c_A}{\partial t}
\end{align}
```

## Step 2: coupling with flux equation


Use the convection–diffusion flux (constant $v_m$):

```{=tex}
\begin{align}
N_A
=
-\,D_{AB}\,\frac{\partial c_A}{\partial z}
+
c_A\,v_m
\end{align}
```

When $v_m$ is constant, differentiate over $N_A$ becomes:

```{=tex}
\begin{align}
\frac{\partial N_A}{\partial z}
=
-\,D_{AB}\,\frac{\partial^2 c_A}{\partial z^2}
+
v_m\,\frac{\partial c_A}{\partial z}
\qquad (v_m=\text{const})
\end{align}
```

## Step 3: general equation for M.T + surface reaction

```{=tex}
\begin{align}
\frac{\partial c_A}{\partial t}
&=
-\left(
-\,D_{AB}\,\frac{\partial^2 c_A}{\partial z^2}
+
v_m\,\frac{\partial c_A}{\partial z}
\right)
+
\frac{4k'}{D}\,(c_{A,s}-c_A) \\
&=
D_{AB}\,\frac{\partial^2 c_A}{\partial z^2}
-
v_m\,\frac{\partial c_A}{\partial z}
+
\frac{4k}{D}\,(c_{A,s}-c_A)
\end{align}
```

Need:

- initial condition $c_A(z,0)$
- boundary conditions at $z=0$ and $z=L$

Solve:

- analytical (special cases)
- numerical integration (finite difference)

## Simplifications for solving U.S.S. problems

We can make some assumptions that do not have significant impact on the results:

- **Assumption 1**: convection $\gg$ diffusion
  - We can write $D_{AB} \frac{\partial^2 c_A}{\partial z^2} \approx 0$
  - Only need $v_m$ to solve the U.S.S. problem
  - Typically tolerable error in industrial pipes

- **Asumption 2**: system close to steady state
  - U.S.S --> S.S.? Just let $\partial c_A/\partial t = 0$
  - Can compare with other S.S. solutions!


## Solutions to simplified U.S.S. governing equations

After removing the $\partial c_A/\partial t$ and  $D_{AB} \frac{\partial^2 c_A}{\partial z^2}$ terms, we have

```{=tex}
\begin{align}
\frac{4k}{D}\left(c_{A,s}-c_A\right)
&= v_m \frac{dc_A}{dz} \\
\int_0^z \frac{4k}{D v_m} dz
&= \int_{c_{Ai}}^{c_A} \frac{dc_A}{c_{A,s}-c_A} \\
\frac{4k}{D v_m} z &= -\ln\!\left(\frac{c_{A,s}-c_A(z)}{c_{A,s}-c_{A0}}\right)
\end{align}
```

We get $c_A(z)$ profile, where $c_{A0}=c_{A}(z=0)$

```{=tex}
\begin{align}
c_A(z)
= c_{A,s}
-\left(c_{A,s} - c_{A0}\right)
\exp\!\left(-\frac{4k}{D v_m} z\right)
\end{align}
```

## Interpretation of $c_A(z)$ profile

For this problem, because the surface reaction occurs, we no longer have a linear $c_A$ profile. It decays with
a length scale of $D v_m / 4k$.

- At the exit of the pipe, concentration of $c_A(L)$ is no less than $c_{A, s}$!
- Decay length $L_{d} \approx \frac{D v_m}{4k}$
- Faster flushing 👉 incomplete absorption
- Is $N_A$ constant inside the tube?
- What is the unit of $k$ in this case?

We will investigate these questions in the second half of the course!

## Case 3: catalytic conversion of D → E (1D, steady state)

**Question**: A binary gas mixture containing species D and E occupies
a stagnant gas film of thickness $L$ in the $z$-direction.  At $z=0$,
the gas is in contact with a solid catalyst surface that
**instantaneously** and **completely** converts D to E.  At $z=L$, the gas
composition is maintained at known values. Assumpt constant $T$ and
total pressure $p_T$ and 100% conversion rate. The reaction between D and E follows:
$$
m \text{D} \rightarrow n \text{E}
$$

Develop the governing differential equation for $N_D$ and $c_D$ the
molar flux of species D in the gas phase at steady state.

## Step 1: mass balance

At anywhere outside the boundary, we have:

```{=tex}
\begin{align}
\text{[In]} - \text{[Out]} + \text{[Gen]} &= \text{[Acc]} \\
-\frac{\partial N_D}{\partial z} + 0 &= \frac{\partial c_D}{\partial t}
\end{align}
```

- Catalyst at the bottom of the reactor 👉 [Gen] = 0
- How do we get the boundary condition?

## Step 2: flux equation

The reaction at the bottom catalyst is very fast, we can use the
"general case" flux equation

```{=tex}
\begin{align}
N_D = -D_{DE} \frac{\partial c_D}{\partial z} + \frac{c_D}{c_T} (N_D + N_E)
\end{align}
```

- How do we get relation between $N_D$ and $N_E$?
- What are the boundary conditions?

## Diffusion-controlled reaction: explanations

In this system we have two conditions **instantaneous** and
**complete** reaction. They have distinct meanings

- **Instantaneous**: the reaction rate at the boundary does not depend
  on the actual concentration, but rather what ever molar flux is at that interface (**diffusion-controlled**)
  - Often we will have $c_{D, z=0} = 0$ (all D at interface consumed instantly)
- **Complete**: the conversion between D and E occur 100%, meaning the fluxes of D and E follow **stoichiometry**
  - Stoichiometry: $m D \rightarrow n E$
  - Flux continuity $N_D / m + N_E / n = 0$

## Step 3: conditions and solutions

We have in general $N_D / m = - N_E / n$ 

```{=tex}
\begin{align}
-\frac{\partial }{\partial z}
\left[
-D_{DE} \frac{\partial c_D}{\partial z}
+ \frac{c_D}{c_T} (N_D + N_E)
\right] &= \frac{\partial c_D}{\partial t} \\
-\frac{\partial }{\partial z}
\left[
-D_{DE} \frac{\partial c_D}{\partial z}
+ \frac{c_D}{c_T} N_D (1 - \frac{n}{m})
\right] &= \frac{\partial c_D}{\partial t}
\end{align}
```

At steady state, we have
```
N_D = \left[-\frac{D_{DE}}{1 - \frac{c_D}{c_T} (1 - \frac{n}{m})}\right]{d c_D}{dz}
```

The steady state solution can be easily integrated

## Catalyst in wall: simulation demo

A slightly adapted demo from lecture 3 ($x_A$ profile). 
Can we modify the molar flux by interface reaction stoichiometry?

```{=html}
<iframe width="100%" height="900"
		src="../../scripts/L11_stoichiometry.html" title="Webpage example"></iframe>
```
 


## Conclusion of unsteady state mass transport

We will cover until **this point** in the mid-term exam!

To solve unsteady and steady state problem, use the following steps:

1. Draw scheme and list physical quantities / conditions
2. Write mass balance equation
3. Is it steady-state or unsteady-state?
4. If unsteady state, write flux equation in differential form
5. If steady state, use one of the solution examples 
6. Do integration / calculation

## Problem-solving checklist

- Write the unsteady-state mass balance first.
- Add the appropriate reaction term and transport relation.
- Apply the correct flux, boundary, and initial conditions.











## Summary

- Coupling diffusion with reaction changes both the governing equation and the boundary conditions.
- Simplifying assumptions can turn difficult reaction-diffusion models into solvable forms.
- Reactive-wall and catalytic examples show how concentration profiles reveal the controlling mechanism.




