---
title: "CHE 318 Lecture 15"
subtitle: "Theories For Mass Transfer Coefficients"
author: "Dr. Tian Tian"
date: "2026-02-06"
format:
  html: {}
  revealjs:
    output-file: slides.html
  pdf:
    output-file: L15.pdf
---

::: {.content-visible when-format="html" unless-format="revealjs"}

::: {.callout-note}
- Slides 👉  [Open presentation🗒️](./slides.html)
- PDF version of course note  👉 [Open in pdf](./L15.pdf)
- Handwritten notes 👉 [Open in pdf](./public/L15_annotated.pdf)
:::

:::


## Learning Outcomes {.center}

After today's lecture, you will be able to:

- Recall theoretical models for mass transfer coefficients
- Understand the "interface thickness" associated with mass transfer
- Analyze different power laws associated with $D_{AB}$ to $k_c'$

## Example 1: Convective Flux Through A Tube


Question: Consider steady-state, one-dimensional mass transfer of a
binary gas mixture consisting of species $A$ and $B$ between two
parallel planes, labeled (1) and (2). The total pressure of the system
is $p_T = 700\ \text{kPa}$ and the temperature is maintained at $T =
100 ^\circ\text{C}$. The gas-phase mass transfer coefficient from molar fraction is 
$k_y’ = 1.5 \times 10^{-4}\ \text{kg mol}\cdot \text{m}^{-2} \cdot \text{s}^{-1}$. Flow in pipe 1 contains 65 mol% A, while flow in pipe 2 contains 45 mol% B.

1. Find the values for fluxes $N_A$ and $N_B$
2. Find the values (and units) for other coefficients $k_G'$ and $k_c'$


## Solutions To Example 1

:::{.callout-tip}
- Mass transport normal to fluid can usually use $k$ to write the flux equation
- Pay attention to the unit used
:::

Answer

1. $N_A = -N_B = 3.0\times 10^{-5}\ \text{kg mol}\cdot \text{m}^{-2} \cdot \text{s}^{-1}$
2. $k_G' = k_y' / p_T = 2.14\times 10^{-7}\ \text{kg mol}/(\text{m}^2 \cdot \text{s} \cdot {kPa})$
3. $k_c' = k_y' RT / p_T = 6.65\times 10^{-4}\ \text{m}\cdot \text{s}^{-1}$

## Example 2: Using $k$ For Diffusion Through Stagnant Film

_Geankoplis Ex 7.2-1_ A large volume of pure gas $B$ at 2 atm pressure
flows over a flat surface. Species $A$ is vaporizing from the surface
into the gas stream. The liquid $A$ completely wets the surface of a
blotting paper, so that the interface is always covered with liquid
$A$. The partial pressure of species $A$ at $298\;\text{K}$ is
$0.20\;\text{atm}$. 
From textbook table, 
$$ k_y' = 6.78 \times 10^{-5} \;\frac{\text{kg mol}}{\text{m}^2 \cdot \text{s}}$$.

Calculate the evaporation rate $N_A$ and determine the values of the gas-phase mass transfer coefficients $k_y$ and $k_G$ for this system.

## Solutions To Example 2

:::{.callout-tip}
- This is a diffusion through stagnant B system
- Convert $k_y'$ to $k_y$ in stagnant B system first
- Express $k_G$ in $\text{kg mol}/(\text{s} \cdot \text{m}^2 \cdot \text{atm})$ first
:::

Answer

1. $y_{Bm} = 0.95$  👉 
$k_y = k_y'/y_{Bm} = 7.138\times 10^{-5} \;\frac{\text{kg mol}}{\text{m}^2 \cdot \text{s}}$
2. $y_G = 3.569 \times 10^{-5}\ \text{kg mol}/(\text{s} \cdot \text{m}^2 \cdot \text{atm})$
3. $N_A = y_G (p_{A1} - p_{A2}) = 7.138 \times 10^{-6}\ \text{kg mol}\cdot \text{m}^{-2} \cdot \text{s}^{-1}$

## Example 3: Measuring $k$ For Actual Systems

Since we have $\text{[Flux]} = k \times \text{[Driving Force]}$, we can measure $k$ using given geometries.

Question: solid benzoic acid (A) in a sphere with radius $r_0$ was
place in a tube with water flowing in the system. The fluid was turned
on for a certain time interval $\Delta t$ to remove dissolved A from
the liquid. The masses of a dried sphere before and after the
experiment were measured to be $m_1$ and $m_2$ ($m_2 - m_1 \ll
m_1$). The solubility of A in water is $c_{As}$ and water contain no
benzoid acid. Calculate the mass transfer coefficient of this
system. What form of $k$ did you use?

## Solutions To Example 3

:::{.callout-tip}
- Flow-induced flux, can be turbulent  👉 lumped $k_L$ term is valid
- Link $N_A$ to mass loss rate
:::

Answer:

- Relating flux equation to mass loss rate:
```{=tex}
\begin{align}
N_A &= \frac{1}{4 \pi r_0^2} \frac{m_1 - m_2}{M_A \Delta t} \\
&= k_L (c_{As} - 0)
\end{align}
```
- Solve for $k_L$:

```{=tex}
\begin{align}
k_L = \frac{1}{4 \pi r_0^2} \frac{m_1 - m_2}{c_{As} M_A \Delta t}
\end{align}
```

## How Can We Predict The $k_c'$ Values?

- $k_c'$ is a convenient parameter, but is system dependent!
- $k_c' = f(D_{AB}, v_m, \mu, \rho, T, \text{[Geometry]}), \dots$
- Several theories attemp to build the form of such relation:
  1. Film mass transfer theory
  2. Penetration theory
  3. Boundary layer theory

- Different forms & applicable scenarios

## Film Mass Transfer Theory

- Nernst (1904) & Whitman (1923), based on convective heat transfer
- Assumptions:
  1. A thin layer with thickness $\delta_f$ exists at the boundary of the interface
  2. Only **diffusive mass transfer** occur in the film
  3. Convection occurs **outside** the film region

## Film Mass Transfer Theory: Equations

Inside the thin film region, we have EMCD-like mass transfer

```{=tex}
\begin{align}
N_A &= J_{Az}^*\\
    &= -D_{AB} \frac{d c_A}{dz}\\
	&= \boxed{\frac{D_{AB}}{\delta_f}} (c_{A, i} - c_{A, b}) \\
	&= k_c' (c_{A, i} - c_{A, b})
\end{align}
```

- Predicts $k_c' \propto D_{AB}^{1.0}$ (Incorrect in most cases)
- Simple prediction of $k_c'$ if we know $\delta_f$
- $\delta_f$ is linked to both $D_{AB}$ and $\epsilon_m$

## Penetration Theory

- Higbie (1935) & Danckwerts (1950) for gas-liquid interface
- Assumptions:
  1. Gas molecules penetrate into laminar film surrounding the interface
  2. The penetration time is usually very short
  3. Fluid makes contact with the gas molecules and return to the bulk
  4. The penetration process can be modeled by time-dependent unsteady state mass transfer!
  
## Penetration Theory: Equations

- Governing equation for mass transfer (no convection in the film)
  ```{=tex}
  \begin{align}
  \frac{\partial c_A}{\partial t}
  = D_{AB}\frac{\partial^2 c_A}{\partial z^2}
  \end{align}
  ```
- B.C. $c_A(z=0)=c_{A,s},\ c_A(z=\infty)=c_{A,b}$

## Penetration Theory: Solutions

The concentration inside the liquid film has the following solution:

  ```{=tex}
  \begin{align}
  \frac{c_A(z, t) - c_{A, b}}{c_{A,s} - c_{A,b}}
  = 1 - \text{erf}\left(
  \frac{z}{\sqrt{4 D_{AB} t}}
  \right)
  \end{align}
  ```

We can directly get $N_A$ from $\frac{\partial c_A}{\partial z}\vert_{\text{surf}}$:

```{=tex}
\begin{align}
N_A(z=0, t) &= -D_{AB} \frac{d c_A}{d t} \\
&= \sqrt{\frac{D_{AB}}{\pi t}} (c_{A,s} - c_{A,b})
\end{align}
```

## Penetration Theory: Power Law

We can calculate the average $N_A$ in the penetration period ($0 < t < t_L$):

```{=tex}
\begin{align}
N_A &= \frac{1}{t_L} \int_0^{t_L} -D_{AB} \frac{d c_A}{d t'} \\
&= \boxed{\sqrt{\frac{4D_{AB}}{\pi t_L}}} (c_{A,s} - c_{A,b}) \\
&= k_c' (c_{A,s} - c_{A,b})
\end{align}
```

- Penetration theory predicts $k_c' \propto D_{AB}^{0.5}$
- Practical power law $k_c' \propto D_{AB}^n;\ n=0.8\sim 0.9$
- Danckwert's renewal model: $k_c' \propto (D_{AB} s)^{0.5}$ 👉 correction to power law using $s$

## Boundary Layer Theory

- Theory connecting fluid dynamics ($v_m=[v_x, v_y]$) and mass transfer coefficient
- Fluid velocity field associate with a boundary thickness $\delta$
- Conversely the concentration in fluid has a boundary $\delta_c$
- Boundary layer theory solves $c_A$ profile using analogs in momentum transfer


## Boundary Layer Theory: Equations

The mass balance equation for a steady-state 2D problem without generation
```{=tex}
\begin{align}
-\nabla \cdot \vec{N_A} &= 0 \\
-\nabla \cdot (\vec{J}_A^* + c_A \vec{v}) &= 0 \\
\vec{v} \cdot \nabla c_A &= D_{AB} \nabla^2 c_A \\
v_x \frac{\partial c_A}{\partial x}
+
v_y \frac{\partial c_A}{\partial y}
&=
D_{AB} \frac{\partial^2 c_A}{\partial y^2}
\end{align}
```

- Mass transfer in $x$-direction (fluid direction) is convective
- Diffusive contribution only occur in $y$-direction (normal to fluid)
- Boundary conditions:
  - $y=0$ (on surface) $\frac{v_x}{v_b} = (c_A - c_{A, s})/(c_{A, b} - c_{A, s}) = 0$
  - $y=\infty$ (center of fluid) $\frac{v_x}{v_b} = (c_A - c_{A, s})/(c_{A, b} - c_{A, s}) = 1$

## Boundary Layer Theory: Concentration Profile

If the boundary thickness for fluid $\delta$ and concentration
$\delta_c$ are same, can use the solution to velocity field:

```{=tex}
\begin{align}
\left(
\frac{\partial c_A}{\partial y}
\right)_{y=0}
= (c_{A, \infty} - c_{A, s})
\left(
\frac{0.332}{x} N_{Re, x}^{0.5}
\right)
\end{align}
```

- Here $N_{Re, x} = x v \rho/\mu$ is the location-dependent Reynolds number (to be discussed later)
- Because $\partial c_A/\partial y$ is known --> we can get the expression for $k_c'$!

## Boundary Layer Theory: Final Results {.smaller}

Boundary layer theory links diffusion in $y$-direction with:
```{=tex}
\begin{align}
N_{Ay} &= k_c' (c_{A,s} - c_{A,b}) \\
       &= \boxed{-D_{AB}  \left(
\frac{0.332}{x} N_{Re, x}^{0.5} 
\right)}
(c_{A, \infty} - c_{A, s})
\end{align}
```

For $\delta=\delta_c$, we have $k_c'$ expression:
```{=tex}
\begin{align}
k_c' = \frac{0.332 D_{AB}}{x} N_{Re, x}^{0.5}
\end{align}
```

Generally, we have Schmidt number $N_{Sc} = (\delta/\delta_c)^3$, so 
```{=tex}
\begin{align}
k_c' = \frac{0.332 D_{AB}}{x} N_{Re, x}^{0.5} N_{Sc}^{1/3}
\end{align}
```

The global mass transfer coefficient should integrate over $0 \sim L$:
```{=tex}
\begin{align}
k_c' = \frac{0.664 D_{AB}}{L} N_{Re}^{0.5} N_{Sc}^{1/3}
\end{align}
```

- where $N_{Re} = (\rho L v)/\mu$ is the overall Reynolds number
- boundary layer theory predicts $k_c' \propto D_{AB}^{2/3}$ (as $N_{Sc} \propto 1/D_{AB}$)

## Comparison Between Theories For $k_c'$

| Approach | Governing expression for $N_A$ | Scaling of $k_c'$ with $D_{AB}$ |
|---|---|---|
| Film theory | $N_A = \frac{D_{AB}}{\delta}\,(c_{A,s} - c_{A,b})$ | $k_c' \propto D_{AB}$ |
| Penetration theory | $N_A = \sqrt{\frac{4D_{AB}}{\pi t_L}}\,(c_{A,s} - c_{A,b})$ | $k_c' \propto D_{AB}^{0.5}$ |
| Boundary layer theory | $N_A = 0.664\,D_{AB}/L\,N_{Sc}^{1/3}\,N_{Re}^{1/2} (c_{As} - c_{A,b})$ | $k_c' \propto D_{AB}^{2/3}$ |
| General formula | -- | $k_c' \propto D_{AB}^n$<br/>$n=0.5\sim 0.9$ |



## Why Do We Need These Dimensionless Numbers?

- Expressing fluxes using $k$ coefficients are easy
- But do we need to measure $k$ for each system specifically?
- Of course **NO**!
- We can correlate the values of $k$ measured in different geometries, velocities using **dimensionless numbers**
- Similar treatment exists in heat and momentum (fluid) transfer

## Dimensionless Numbers In Mass Transfer {.smaller}

- **General form**: $N_{\text{name}} = \dfrac{\text{Scale of effect 1}}{\text{Scale of Effect 2}}$

- **Schmidt number** (ratio between momentum diffusivity and molecular diffusivity)

```{=tex}
\begin{align}
N_{\text{Sc}} = \frac{\mu}{\rho D_{AB}}
\end{align}
```

- **Sherwood number** (ratio between convective mass transfer and molecular mass transfer)

```{=tex}
\begin{align}
N_{\text{Sh}} = \frac{k_c' L}{D_{AB}}
\end{align}
```

- **Reynolds number** (ratio between kinetic vs viscous forces of fluid flow)

```{=tex}
\begin{align}
N_{\text{Re}} = \frac{L v \rho}{\mu}
\end{align}
```
  - $L$: characteristic length of system
  - Location specific $N_{\text{Re}, x}$ also used

## How Are $k_c'$ Correlated By Dimensionless Numbers?

- Idea: mass transfer in flowing fluid described by $v$, $\rho$, $\mu$, $c$, $D_{AB}$ and geometry (characteristic length $L$)
- The combinations of these properties --> dimensionless number groups ($N_{\text{Sc}}$, $N_{\text{Sh}}$, $N_{\text{Re}}$)
- The Chilton-Colburn $j$-factor analog has most successful use in mass transfer

```{=tex}
\begin{align}
j_D &= f/2 \\
&= \frac{k_c'}{v_{av}} (N_{\text{Sc}})^{2/3} \\
    &= \boxed{\frac{k_c' L}{D_{AB}}} \boxed{\frac{\rho D_{AB}}{\mu}} \boxed{\frac{\mu}{L v_{av} \rho}} (N_\text{sc})^{2/3} \\
	&= N_{\text{Sh}} N_{\text{Sc}}^{-1} N_{\text{Re}}^{-1} (N_\text{sc})^{2/3} \\
	&= \frac{N_{\text{Sh}}}{N_{\text{Re}} N_{\text{Sc}}^{1/3}}
\end{align}
```

- $f$ is the Fanning Friction Factor (can be found in table)

## General Procedure To Calculate $k_c'$ {.smaller}

1. Calculate Reynolds number $N_{Re}$ from fluid properties + geometry

2. Determine flow regime (liquid)

  - $N_{Re} < 2100$ → laminar flow
  - $N_{Re} \ge 2100$ → turbulent flow

3. Evaluate friction factor $f$  

  - Laminar flow:  
    $$
    f = \frac{16}{N_{Re}}
    $$
  - Turbulent flow:  
    $$
    f = \frac{\tau_s}{\tfrac12 \rho v^2},\qquad
    \tau_s = \frac{\Delta P_f\,\pi R^2}{2\pi R\,\Delta L}
    $$

4. Compute mass-transfer $j$-factor  
  $$
  j_D = \frac{f}{2}
  $$

5. Obtain mass-transfer coefficient  
  $$
  k_c' = j_D\,v_{av}\,N_{Sc}^{-2/3}
  $$

## Use of Empirical Mass Transfer Laws

- In many systems, flux and / or concentration profiles become hard to have simple form
- Luckily we can simplify typical mass transfer problems as different geometries
  - Cyliner / Pipe
  - Parallel plates
  - Flow around sphere
  - Packed bed
- We will show a few case studies for different geometries
- Dimensionless numbers ($N_{Re}$, $N_{Sc}$, $N_{Sh}$) help determine governing equations

## Case 1: Mass Transfer for Flow Inside Pipes

- Usually use the Linton & Sherwood chart
- Valid for gas / liquid in both laminar & turbulent regimes

## Flow Inside Pipes: Solution Procedure

- Governing dimensionless quantity:

```{=tex}
\begin{align}
\frac{W}{D_{AB}\rho L} &= N_{Re}N_{Sc} \frac{D}{L} \frac{\pi}{4} \\
&= \frac{\text{[Total Forced Flow]} \text{(kg/s)}}{\text{[Total Diffusive Flow]} \text{(kg/s)}}
\end{align}
```

- If gas 👉 use the "rodlike flow" line
- If liquid, distinguish 2 cases
  - parabolic flow ($N_{Re} < 2100;\ \frac{W}{D_{AB}\rho L} > 400$)
  - turbulent flow ($N_{Re} > 2100;\ 0.6 < N_{Sc} < 3000$)

## Flow Inside Pipes: Solution For Liquid

:::{.columns}
:::{.column width="50%"}
**Parabolic flow**

```{=tex}
\begin{align}
\frac{c_A - c_{A,s}}{c_{A,i} - c_{A,s}}
&= 5.5
\left[
\frac{W}{D_{AB}\,\rho\,L}
\right]^{-\tfrac{2}{3}}
\end{align}
```

- $c_A$: exit concentration
- $c_{A,i}, c_{A,s}$: inlet & surface concentration
- $W$: flow rate in (kg/s)

- $k_c'$ can be calculated by $j_D$
:::

:::{.column width="50%"}
**Turbulent flow**

```{=tex}
\begin{align}
N_{Sh}
&= k_c'\left(\frac{D}{D_{AB}}\right) \\
&= \frac{k_c\,p_{BM}}{P}
\left(\frac{D}{D_{AB}}\right) \\
&= 0.023
\left(\frac{\rho D v}{\mu}\right)^{0.83}
\left(\frac{\mu}{\rho D_{AB}}\right)^{0.33} \\
&= 0.023\,
N_{Re}^{0.83}\,
N_{Sc}^{0.33}
\end{align}
```

- Similar to the $j_D$ analog
- Just need $N_{Re}$ and $N_{Sc}$ to determine $k_c'$
- Characteristic length $D$ is pipe diameter!
:::

## Case 2: Flow Past Parallel Plates

- Can be used for gases or evaporation of liquid
- Distinguished between laminar & turbulent flow
- $N_{Re}$ regime cutoff different in gas & liquid!
- - Characteristic length $L$: length of plate in flow direction

## Flow Past Parallel Plates: Results

:::{.columns}
:::{.column width="50%"}
**Laminar flow** ($N_{Re} < 15,000$)

```{=tex}
\begin{align}
j_D &= 0.664 N_{Re, L}^{-0.5} \\
\frac{k_c' L}{D_{AB}} &= 0.664 N_{Re, L}^{0.5}
N_{Sc}^{1/3}
\end{align}
```
- This follows our derivation of boundary layer theory


:::

:::{.column width="50%"}
**Turbulent flow**

- Gas: $15,000 < N_{Re}< 300,000 $

```{=tex}
\begin{align}
j_D = 0.036 N_{Re, L}^{-0.2}
\end{align}
```

- Liquid: $600 < N_{Re}< 50,000$
```{=tex}
\begin{align}
j_D = 0.99 N_{Re, L}^{-0.5}
\end{align}
```

::: 
:::

## Case 3: Flow Past Single Sphere 

- Frequent geometry in particle solutions
- Low Reynolds regime 👉 solution for stagnant diffusion on spherical surface
- High Reynolds regime 👉 correct $N_{Sh}$ and back calculate $k_c'$

## Flow Past Single Sphere: Results

:::{.columns}
:::{.column width="35%"}
**Low Reynolds** ($N_{Re} < 2$)

```{=tex}
\begin{align}
N_A &= \boxed{\frac{2 D_{AB}}{D_p}} (c_{A1} - c_{A2}) \\
    &= k_c (c_{A1} - c_{A2}) \\
	&= \frac{k_c'}{x_{Bm}}(c_{A1} - c_{A2}) \\
\end{align}
```

- For $x_{Bm} \approx 1$, we have:

$$
k_c' = \frac{2D_{AB}}{D_p}
$$

- Sherwood number: $N_{Sh} = 2$

:::


:::{.column width="65%"}

**High Reynolds** ($N_{Re} > 2$)

- Gas:
```{=tex}
\begin{align}
&N_{Sh} = 2 + 0.552 N_{Re}^{0.53} N_{Sc}^{1/3} \\
&0.6 < N_{Sc} < 2.7\;\ N_{Re} < 48000
\end{align}
```

- Liquid:
```{=tex}
\begin{align}
N_{Sh} &= 2 + 0.95 N_{Re}^{0.5} N_{Sc}^{1/3};\ N_{Re} < 2000\\
N_{Sh} &= 0.347 N_{Re}^{0.62} N_{Sc}^{1/3};\ 2000 < N_{Re} < 17000
\end{align}
```

- Back calculate $k_c' = N_{Sh} \frac{D_{AB}}{D_p}$
:::
:::

## Case 4: Mass Transfer for Packed Beds

- Very common geometry for chemical engineering
  - Adsorption and desorption through solid particles (gases and liquids)
  - Catalytic processes with very large surface area

- Geometry characteristics: void fraction $\varepsilon$:
  $$
  \varepsilon
  = \frac{\text{void space}}{\text{total space}}
  = \frac{\text{void space}}{\text{void space} + \text{solid space}}
  $$
  - Typically $0.3 < \varepsilon < 0.5$
  - Void fraction is difficult to measure experimentally
  
## Correlation Equations In Packed Bed

Correlation 1, applicable to:

- gase with $10 < N_{Re} <10,000$
- liquid with $10 < N_{Re} < 1500$

```{=tex}
\begin{align}
j_D &= j_H = \frac{0.4548}{\varepsilon} N_{Re}^(-0.4069) \\
N_{Re} &= \frac{D_p v' \rho}{\mu}
\end{align}
```

- $D_p$: (average) particle diameter
- $v’$: superficial velocity in the tube without packing

## Correlation Equations In Packed Bed (II)

Correlation 2, applicable to:

- liquid with $0.0016 < N_{Re} < 55$, $165 < N_{Sc} < 70000$

```{=tex}
\begin{align}
j_D = \frac{1.09}{\varepsilon}
N_{Re}^(-2/3)
\end{align}
```


- liquid with $55 < N_{Re} < 1500$, $165 < N_{Sc} < 10690$

```{=tex}
\begin{align}
j_D = \frac{0.250}{\varepsilon}
N_{Re}^(-0.31)
\end{align}
```

## Correlation Equations In Packed Bed (III)

Correlation 3, applicable to fluidized beds

-  $10 < N_{Re} < 4000$ (gas & liquid)

```{=tex}
\begin{align}
j_D = \frac{0.4548}{\varepsilon}
N_{Re}^(-0.4069)
\end{align}
```

-  $1 < N_{Re} < 10$ (liquid only)

```{=tex}
\begin{align}
j_D = \frac{1.1068}{\varepsilon}
N_{Re}^(-0.72)
\end{align}
```

## Packed Bed Calculation Steps

1. Known value from operational column: $\varepsilon$, $V_b$ (total volume), $D_p$, $D_{AB}$, $\mu$, $\rho$, etc.
2. Depend on the operational range, calculate $N_{Re}$, $N_Sc$ 👉 choose the equation for $j_D$
3. Obtain $k_c$ from $j_D$ value
4. Calculate flux $N_A$
5. Estimate effective area $A_{eff}$ inside the columne 👉  $\overline{N}_A = A_{eff} N_A$

## A Few Caveats In Packed Bed Problems

- Estimate the effective area?
  - First calculate the effective surface area per volume $a$ then $A_{eff}$
```{=tex}
\begin{align}
a &= \frac{6 (1 - \varepsilon)}{D_p} \\
A_{eff} &= a V_b
\end{align}
```

- Use log-mean driving force correction

```{=tex}
\begin{align}
\overline{N}_A &= A_{eff} N_A \\
&= A_{eff} k_c \frac{
(c_{A, i} - c_{A1}) - (c_{A, i} - c_{A2})}
{
\ln\!\frac{(c_{A, i} - c_{A1})}{(c_{A, i} - c_{A2})}
}
\end{align}
```
where

- $c_{A, i}$: surface concentration
- $c_{A1}, c_{A2}$: in- and outlet concentrations

- Mass-flow balance

```{=tex}
\begin{align}
\overline{N}_A &= A_{eff} N_A \\
&= V (c_{A2} - c_{A1})
\end{align}
```
where $V$ is the volumetric flow rate








